### ISSUE TITLE
Input Field Color Red

### ISSUE THREAD

**Issue by KhairUnNisa10** [Noreen-Jamil/google-signup#1]
![image](https://user-images.githubusercontent.com/49787331/82344946-1a51a780-9a0e-11ea-8256-1f87ba5856d2.png)

The red color of border shouldn't appear on simple output. The borders should be grey.

**Comment by Noreen-Jamil** [comment]
Mam i have done both i will send u another file

**Comment by Noreen-Jamil** [comment]
Mam i have updated the file
